"""Regression tests against intact transforms from the public ABC preview."""

from __future__ import annotations

import mujoco
import numpy as np
import pytest

from abc_geometry.kinematics import (
    RIGHT_ARM_SHARED_TRANSLATION,
    Pose,
    YAMKinematics,
    forward_kinematics,
)

# This ungated Voxel51 mirror contains the raw source record used below:
# https://huggingface.co/datasets/Voxel51/ABC-130k/blob/main/data/val/
# fold_and_stack_the_skirts/episode_aa015e3a-8cb9-4e03-93a9-900fac9ae6b8/
# episode.fo.mcap
# Dataset revision: 9659e8ce4b39580f48369cc31bc2e47a217c40e7.
#
# The first messages on /left-arm-state and /right-arm-state (sequence 0,
# 2025-04-03T17:28:55.850143744Z) preserve both joint angles and 4x4 transforms.
# The fixture is intentionally literal rather than generated by this package:
# it is independent ground truth for geometry recovery on records missing poses.
PUBLIC_INTACT_RECORD = {
    "left_joints": np.array(
        [
            -0.48161287861448265,
            0.7116426337071786,
            0.7040131227588304,
            -0.7028686961165764,
            -0.012016479743651942,
            -0.13103685053788006,
        ]
    ),
    "left_transform_arm_local": np.array(
        [
            [-0.632531141717365, 0.3756759502397681, 0.6773270518510042, 0.2229318922544835],
            [0.18317820509999394, 0.9222451495056406, -0.3404550328452526, -0.11421321941931482],
            [-0.7525623561765962, -0.09127685700529321, -0.6521644236242606, 0.1754101887061787],
            [0.0, 0.0, 0.0, 1.0],
        ]
    ),
    "right_joints": np.array(
        [
            0.43926909285114846,
            1.0530632486457616,
            0.7162203402761875,
            -0.7997634851606019,
            -0.03337911039902686,
            0.0997558556496525,
        ]
    ),
    "right_transform_shared_bimanual": np.array(
        [
            [-0.8605964623532097, -0.35379918654529247, 0.3663329968553596, 0.21752706566379915],
            [-0.2944080765331712, 0.9325444245486542, 0.20900904457763797, -0.5015181464597505],
            [-0.41556902369784254, 0.0720210513885209, -0.906705770743582, 0.08778088368163128],
            [0.0, 0.0, 0.0, 1.0],
        ]
    ),
}


@pytest.fixture(scope="module")
def kinematics() -> YAMKinematics:
    return YAMKinematics()


def test_bundled_model_is_minimal_six_dof_chain(kinematics: YAMKinematics) -> None:
    model = kinematics._model
    assert model.nq == 6
    assert model.njnt == 6
    assert model.nsite == 1
    assert mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_SITE, 0) == "grasp_site"


def test_left_pose_matches_public_intact_record(kinematics: YAMKinematics) -> None:
    pose = kinematics.grasp_pose(
        PUBLIC_INTACT_RECORD["left_joints"],
        arm="left",
        frame="arm_local",
    )

    np.testing.assert_allclose(
        pose.homogeneous_matrix,
        PUBLIC_INTACT_RECORD["left_transform_arm_local"],
        rtol=0.0,
        atol=2e-15,
    )


def test_right_pose_matches_public_shared_frame_record(kinematics: YAMKinematics) -> None:
    pose = kinematics.grasp_pose(
        PUBLIC_INTACT_RECORD["right_joints"],
        arm="right",
        frame="shared_bimanual",
    )

    np.testing.assert_allclose(
        pose.homogeneous_matrix,
        PUBLIC_INTACT_RECORD["right_transform_shared_bimanual"],
        rtol=0.0,
        atol=2e-15,
    )


def test_shared_right_frame_is_empirical_base_translation(
    kinematics: YAMKinematics,
) -> None:
    local = kinematics.grasp_pose(PUBLIC_INTACT_RECORD["right_joints"], arm="right")
    shared = kinematics.grasp_pose(
        PUBLIC_INTACT_RECORD["right_joints"],
        arm="right",
        frame="shared_bimanual",
    )

    np.testing.assert_array_equal(shared.position - local.position, RIGHT_ARM_SHARED_TRANSLATION)
    np.testing.assert_allclose(shared.quaternion_wxyz, local.quaternion_wxyz, atol=0.0)


def test_pose_conventions_and_convenience_api() -> None:
    pose = forward_kinematics(PUBLIC_INTACT_RECORD["left_joints"])

    assert isinstance(pose, Pose)
    np.testing.assert_array_equal(pose.matrix, pose.homogeneous_matrix)
    np.testing.assert_allclose(pose.as_vector()[:3], pose.position, rtol=0.0, atol=0.0)
    np.testing.assert_allclose(
        pose.as_vector()[3:],
        pose.quaternion_wxyz,
        rtol=0.0,
        atol=0.0,
    )
    assert pose.quaternion_wxyz[0] >= 0
    np.testing.assert_allclose(np.linalg.norm(pose.quaternion_wxyz), 1.0, atol=2e-16)


@pytest.mark.parametrize(
    ("joints", "kwargs", "match"),
    [
        ([0.0] * 5, {}, "shape"),
        ([0.0] * 5 + [np.nan], {}, "finite"),
        ([0.0] * 6, {"arm": "center"}, "arm"),
        ([0.0] * 6, {"frame": "world"}, "frame"),
    ],
)
def test_invalid_inputs_raise_clear_errors(
    kinematics: YAMKinematics,
    joints: list[float],
    kwargs: dict[str, str],
    match: str,
) -> None:
    with pytest.raises(ValueError, match=match):
        kinematics.grasp_pose(joints, **kwargs)
